type User @table {
  displayName: String!
  createdAt: Timestamp!
  email: String
  photoUrl: String
}

type QrCode @table {
  data: String!
  qrType: QrType!
  createdAt: Timestamp!
  name: String
  foregroundColor: String
  backgroundColor: String
  logoUrl: String
  publicLink: String
  user: User
}

type QrType @table {
  typeName: String!
  description: String!
}

type Log @table {
  actionType: String!
  timestamp: Timestamp!
  details: String
  user: User
  qrCode: QrCode
}